:toc: macro
:toc-title:
:toclevels: 99

# JavaScript Coding Standards
JavaScript coding standards at littleBits.

toc::[]




## Installation

```
npm install --save-dev eslint-config-littlebits
```



## About

link:http://littlebits.cc[littleBits] writes a lot of JavaScript. We use
link:http://eslint.org/[ESLint] to catch basic errors and enforce a coding
style that we think optimizes *modernity* and *clarity*.

All projects by littleBits written in JavaScript should use the ESLint
configuration found here. Any disagreements should be opened as Github Issues
on this repo.



## Usage

. Have ESLint link:http://eslint.org/docs/user-guide/integrations#editors[integrated into your editor of choice].
. Do `npm install --save-dev eslint-config-littlebits` to bring the config into your project.
. Do `echo 'extends: littlebits' > .eslintrc` to link:http://eslint.org/docs/user-guide/configuring#extending-configuration-files[apply this config] to your project.


## Overriding

If your project has special needs you may apply project-specific overrides as link:http://eslint.org/docs/user-guide/configuring#extending-configuration-files[documented here].



## Versioning Policy

* If new rules are added then release is considered breaking.
** Unless the rule can be automatically fixed in which case the change should be considered non-breaking.
* If new rules are removed then release is considered non-breaking.
